---
abstract: 'merge historical activity of RT users.'
author:
  - 'Ruslan Zakirov <ruz@bestpractical.com>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-MergeUsersHistory
no_index:
  directory:
    - etc
    - html
    - po
    - var
    - inc
requires:
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
